### ISSUE TITLE
PKCE example needed

### ISSUE THREAD

**Issue by ifloppy** [IO-Design-Team/oauth_flutter#1]
Hello. I’m new here.

PKCE support is briefly mentioned in the README, but there is no example provided.

Could you please provide an example of PKCE authorization? Thank you!

**Comment by Rexios80** [comment]
The `oauth_flutter` plugin should handle it automatically. Is there something missing?

**Comment by ifloppy** [comment]
Thank you for your answer. Nothing seemed to be missing.

I encountered a problem. After starting authentication, a white window popped up and disappeared immediately. Then I got the exception `No code found`.

I can access the address in the url variable normally and jump to the page with my custom scheme in my browser.

Please tell me what ridiculous mistake I made in my code, thanks!

![image](https://github.com/user-attachments/assets/04ba2cfe-f8b3-4960-9975-13c6458576a1)

This is a part of my code:
```
Future<void> main() async {
  await Hive.initFlutter();

  redirectUrl = Uri.parse('scheme-here://auth');

  client = OAuth2Client(
    key: 'app-id-here',
    dio: Dio(BaseOptions(baseUrl: 'https://xxxxx/api/user')),
    endpoints: OAuth2Endpoints(
      authorization: 'https://xxxxx/oauth/authorize',
      token: 'https://xxxxx/oauth/token',
    ),
    redirectUri: Uri.parse('scheme-here://auth'),
    credentials: const OAuth2ClientCredentials(
      id: 'app-id-here',
      secret: '',
    ),
    scope: {'openid'},
  );

  runApp(MyApp());
}
```

**Comment by Rexios80** [comment]
The `No code found` exception means the service you are attempting to OAuth with didn't respond with a code value. I haven't had any issue with any OAuth providers I've tried. What provider are you using? Are you sure it has PKCE support?

**Comment by ifloppy** [comment]
Thank you.

The provider is not well-known, but it supports PKCE, which I have enabled in my app.

I can retrieve the callback URL with the code query in my browser using the authorize URL (the `url` that oauth_flutter generated).

However, the popup window does not prompt me to enter my account and password. Additionally, I encountered the following message in my debug console (though I'm unsure if it's related):

```
../../../flutter/shell/platform/embedder/embedder.cc (2928): 'FlutterEngineOnVsync' returned 'kInternalInconsistency'. Could not notify the running engine instance of a Vsync event.
```

How can I print the full callback URL with my custom scheme in the console to better understand what is happening?

**Comment by Rexios80** [comment]
Can you set a breakpoint in `lib/src/model/oauth_authorization.dart` line 31 and check the query parameters that get parsed?

**Comment by ifloppy** [comment]
The breakpoint doesn't work. (The step buttons is still disabled, and the variables window is empty)

I tried to print the `parameters` in the console:

```
{client_id: xxxx, response_type: code, redirect_uri: xxx-client://auth, scope: openid, aud: https://xxx/api/user, nonce: xxxxxx, state: xxxx, code_challenge: xxxx, code_challenge_method: S256}
```

**Comment by ifloppy** [comment]
I solved this by adding parameter `callbackUrlScheme` to `OAuth2Client`. Thank you for your help!
