### ISSUE TITLE
Question on token storage

### ISSUE THREAD

**Issue by ifloppy** [IO-Design-Team/oauth_flutter#3]
Excuse me, does oauth_flutter automatically save and load tokens? If not, how can I save and load the token? Thank you for your patience in answering my question.

**Comment by Rexios80** [comment]
Yes it handles token storage automatically

**Comment by Rexios80** [comment]
Also for questions like this I would much rather communicate on Discord if that's something you're comfortable with. I have a server link in my GitHub profile.

**Comment by ifloppy** [comment]
> Yes it handles token storage automatically

I restarted the application, and it asked me to click authorize button on oauth page(client.isAuthenticated() == false). Is this the correct behavior?

Thank you.

> Also for questions like this I would much rather communicate on Discord if that's something you're comfortable with. I have a server link in my GitHub profile.

I'm worried that instant messaging may affect your work and rest.
